# .github/workflows/keep-awake.yml
name: Keep Streamlit awake

on:
  # run every 10 h (12 h is the sleep threshold, so stay below it)
  schedule:
    - cron: '0 */10 * * *'
  # let you run it manually from the Actions tab
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Quick HTTP hit – works if Streamlit hasn’t changed the rules
      - name: Curl the app
        run: curl -sSL https://cool-demo.streamlit.app || true

      # 2️⃣ Guaranteed “real visit” via Playwright
      - name: Install Playwright
        run: |
          pip install --upgrade playwright
          playwright install chromium
      - name: Open app in headless browser
        run: |
          python - <<'PY'
          from playwright.sync_api import sync_playwright
          with sync_playwright() as p:
              browser = p.chromium.launch()
              page = browser.new_page()
              page.goto("https://eq-solver.streamlit.app")
              page.wait_for_timeout(5000)   # 5 s is plenty for the WS handshake
              browser.close()
          PY
